export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_THEME_CONFIG = 'SET_THEME_CONFIG';
export const SET_ASSEMBLY_SIZE = 'SET_ASSEMBLY_SIZE'
export const SET_TOKEN = 'SET_TOKEN'

// menu
export const UPDATE_COLLAPSE = 'UPDATE_ASIDE_COLLAPSE';
export const SET_MENU_LIST = 'SET_MENU_LIST';


export const SET_BREADCRUMB_LIST = 'SET_BREADCRUMB_LIST'


